import test from 'node:test';
import assert from 'node:assert/strict';
import { leadSchema, escapeHtml, projectTypes } from '../lib/lead-schema.ts';
import { z } from 'zod';
import { legacyPayload, legacyReceipt } from '../lib/legacy-payload.ts';
import { notificationMessage } from '../lib/email-message.ts';
import { projectBrief } from '../lib/project-brief.ts';
const valid={kind:'devis',firstName:'Berekia',lastName:'Kalonji',email:'nexoradigitalrdc@gmail.com',projectType:'sites-web',objective:'Créer un site professionnel pour mon entreprise.',consent:true,requestId:'76cbe46e-526b-4a26-9af5-13f716d409d0',startedAt:Date.now()-5000};
test('A complete quote is accepted; missing consent and project type are refused',()=>{assert.equal(leadSchema.safeParse(valid).success,true);assert.equal(leadSchema.safeParse({...valid,consent:false}).success,false);assert.equal(leadSchema.safeParse({...valid,projectType:''}).success,false);});
test('Oversized input and malformed request IDs are rejected',()=>{assert.equal(leadSchema.safeParse({...valid,objective:'a'.repeat(4001)}).success,false);assert.equal(leadSchema.safeParse({...valid,requestId:'injected'}).success,false);assert.equal(leadSchema.safeParse({...valid,admin:true}).success,false);});
test('A script URL cannot enter the notification as a project link',()=>{assert.equal(leadSchema.safeParse({...valid,existingUrl:'javascript:alert(1)'}).success,false);assert.equal(leadSchema.safeParse({...valid,existingUrl:'https://example.com/project'}).success,true);});
test('User-supplied HTML is escaped before composing the notification',()=>{const lead=leadSchema.parse({...valid,objective:'<script>alert("x")</script> <a href="javascript:alert(1)">Test</a>'});const message=notificationMessage(lead,'NX-TEST');assert.ok(!message.html.includes('<script>'));assert.ok(message.html.includes('&lt;script&gt;'));assert.ok(message.html.includes('&quot;'));assert.equal(escapeHtml("<&'\""),'&lt;&amp;&#39;&quot;');});
test('Contact requests need a meaningful subject and a valid email',()=>{assert.equal(leadSchema.safeParse({...valid,kind:'contact',projectType:'',subject:''}).success,false);assert.equal(leadSchema.safeParse({...valid,kind:'contact',projectType:'',subject:'Partenariat',email:'bad\n@example.com'}).success,false);assert.equal(leadSchema.safeParse({...valid,kind:'contact',projectType:'',subject:'Partenariat'}).success,true);});
test('The mail fallback preserves qualification fields and refuses a brief that would be truncated',()=>{const lead=leadSchema.parse({...valid,country:'RDC',projectStage:'existant',existingUrl:'https://example.com',features:'Gestion des commandes',message:'Une précision utile'});const brief=projectBrief(lead);for(const value of ['Berekia','Kalonji','RDC','Projet à moderniser','https://example.com','Gestion des commandes','Une précision utile'])assert.ok(brief.includes(value));assert.equal(leadSchema.safeParse({...valid,objective:'a'.repeat(4000),features:'b'.repeat(2000)}).success,false);});
// Published external API contract, read from Sites version 6. This catches
// mismatches that our own frontend/server validation cannot detect.
const transportContract=z.object({key:z.uuid(),kind:z.enum(['contact','devis']),name:z.string().min(2).max(120),email:z.email().max(254),company:z.string().max(160),phone:z.string().max(40),subject:z.string().max(160),message:z.string().min(20).max(5000),service:z.string().max(100),budget:z.string().max(80),deadline:z.string().max(80),website:z.literal(''),consent:z.literal(true)}).refine(d=>d.kind!=='devis'||['Sites web','Applications','Outils de gestion','UI/UX Design','Transformation numérique','Solutions sur mesure'].includes(d.service));
test('Every new quote category satisfies the existing mail transport contract',()=>{for(const projectType of projectTypes){const lead=leadSchema.parse({...valid,projectType,budget:'3000-10000',deadline:'1-3-mois'});const payload=legacyPayload(lead);assert.equal(transportContract.safeParse(payload).success,true,projectType);assert.equal(payload.key,lead.requestId);assert.ok(payload.message.includes('Type de projet :'));assert.equal(payload.budget,'3 000 à 10 000 USD');assert.equal(payload.deadline,'Dans 1 à 3 mois');}assert.equal(transportContract.safeParse(legacyPayload(leadSchema.parse({...valid,kind:'contact',projectType:'',subject:'Partenariat'}))).success,true);});
test('Long names stay complete in the brief without violating the transport limit',()=>{const firstName='A'.repeat(80),lastName='B'.repeat(100);const lead=leadSchema.parse({...valid,firstName,lastName});const payload=legacyPayload(lead);assert.equal(transportContract.safeParse(payload).success,true);assert.ok(payload.message.includes('Prénom : '+firstName));assert.ok(payload.message.includes('Nom : '+lastName));assert.ok(payload.name.endsWith(lastName));});
test('A successful HTTP response without an accepted mail receipt cannot claim delivery',()=>{for(const body of [null,{}, {reference:'NX-TEST'},{emailSent:false,reference:'NX-TEST'},{emailSent:true,reference:''}])assert.throws(()=>legacyReceipt(body));assert.deepEqual(legacyReceipt({emailSent:true,reference:'NX-TEST'}),{reference:'NX-TEST',confirmationSent:false});});
