'use client';
import { useEffect, useRef, useState, type ChangeEvent, type FormEvent, type ReactNode } from 'react';
import Link from 'next/link';
import { CircleCheck, LockKeyhole } from 'lucide-react';
import { Button } from '@/components/ui';
import { leadSchema, projectTypes, type Lead } from '@/lib/lead-schema';
import { site } from '@/lib/config';
import { projectTypeLabels as typeLabels } from '@/lib/project-labels';
type FormValues=Omit<Lead,'consent'|'requestId'|'startedAt'>&{consent:boolean};
const initialValues=(kind:'contact'|'devis',initialService=''):FormValues=>({kind,firstName:'',lastName:'',company:'',email:'',phone:'',country:'RDC',projectType:projectTypes.includes(initialService as typeof projectTypes[number])?initialService as typeof projectTypes[number]:'',objective:'',features:'',budget:'',deadline:'',projectStage:'',existingUrl:'',subject:'',message:'',consent:false,website:''});
function Field({name,label,optional,error,wide,children}:{name:string;label:string;optional?:boolean;error?:string;wide?:boolean;children:ReactNode}){return <div className={`field ${wide?'field-wide':''}`}><label htmlFor={name}>{label}{optional?<span className="optional">facultatif</span>:<span aria-hidden="true"> *</span>}</label>{children}{error&&<p className="field-error" id={`${name}-error`}>{error}</p>}</div>;}
export function ProjectForm({kind='devis',initialService=''}:{kind?:'contact'|'devis';initialService?:string}) {
  const [values,setValues]=useState<FormValues>(()=>initialValues(kind,initialService));const [step,setStep]=useState(0);const [errors,setErrors]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [failure,setFailure]=useState('');const [receipt,setReceipt]=useState<{reference:string;confirmationSent:boolean}|null>(null);
  useEffect(()=>{if(receipt){const result=document.getElementById('form-result');result?.focus();result?.scrollIntoView({block:'center',behavior:'auto'});}},[receipt]);
  const started=useRef<number|undefined>(undefined);const requestId=useRef<string|undefined>(undefined);const heading=useRef<HTMLHeadingElement>(null);
  function update(event:ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>){if(!started.current)started.current=Date.now();const {name,value}=event.target;const next=event.target instanceof HTMLInputElement&&event.target.type==='checkbox'?event.target.checked:value;setValues(v=>({...v,[name]:next}));setErrors(prev=>({...prev,[name]:''}));setFailure('');requestId.current=undefined;}
  function fieldProps(name:keyof FormValues){return {id:name,name,value:String(values[name]),'aria-invalid':!!errors[name] as boolean,'aria-describedby':errors[name]?`${name}-error`:undefined};}
  function move(next:number){setStep(next);setTimeout(()=>heading.current?.focus(),0);}
  function validate(fields?:string[]){const parsed=leadSchema.safeParse({...values,consent:values.consent,requestId:requestId.current||crypto.randomUUID(),startedAt:started.current||Date.now()-1000});if(parsed.success){setErrors({});return true;}const selected=parsed.error.issues.filter(i=>!fields||fields.includes(String(i.path[0])));const e:Record<string,string>={};for(const issue of selected)e[String(issue.path[0])]=issue.message;setErrors(e);if(selected.length){setTimeout(()=>document.getElementById(String(selected[0].path[0]))?.focus(),0);return false;}return true;}
  function next(){if(validate(step===0?['projectType','objective']:['features','message','existingUrl','budget','deadline','projectStage']))move(step+1);}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;if(kind==='devis'&&step<2){next();return;}if(!validate())return;setBusy(true);setFailure('');requestId.current ||= crypto.randomUUID();try{const response=await fetch('/api/demandes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,requestId:requestId.current,startedAt:started.current||Date.now()-2000})});const result=await response.json();if(!response.ok){if(result.fields)setErrors(result.fields);throw new Error(result.error||'Votre demande n’a pas pu être transmise.');}setReceipt(result);window.dispatchEvent(new CustomEvent('nexora:conversion',{detail:kind}));}catch(error){setFailure(error instanceof Error?error.message:'La connexion a été interrompue. Réessayez.');}finally{setBusy(false);}}
  if(receipt)return <div className="project-form form-success" id="form-result" role="status" tabIndex={-1}><CircleCheck size={48}/><h2>Votre demande est transmise.</h2><p>Merci {values.firstName}. Nous allons étudier votre besoin et revenir vers vous à l’adresse indiquée.</p><span className="form-reference">Référence : {receipt.reference}</span>{receipt.confirmationSent&&<p>Un e-mail de confirmation vous a également été envoyé.</p>}<Link href="/realisations" className="button button-secondary">Découvrir nos projets</Link></div>;
  const coordinates=<><Field name="firstName" label="Prénom" error={errors.firstName}><input {...fieldProps('firstName')} onChange={update} autoComplete="given-name" maxLength={80} required/></Field><Field name="lastName" label="Nom" error={errors.lastName}><input {...fieldProps('lastName')} onChange={update} autoComplete="family-name" maxLength={100} required/></Field><Field name="email" label="E-mail" error={errors.email} wide><input {...fieldProps('email')} onChange={update} type="email" autoComplete="email" inputMode="email" maxLength={254} required placeholder="vous@entreprise.com"/></Field><Field name="company" label="Entreprise / organisation" optional error={errors.company} wide><input {...fieldProps('company')} onChange={update} autoComplete="organization" maxLength={160}/></Field><Field name="phone" label="Téléphone" optional error={errors.phone}><input {...fieldProps('phone')} onChange={update} type="tel" inputMode="tel" autoComplete="tel" maxLength={40} placeholder="+243 …"/></Field><Field name="country" label="Pays" optional error={errors.country}><input {...fieldProps('country')} onChange={update} autoComplete="country-name" maxLength={100}/></Field></>;
  return <form className="project-form" onSubmit={submit} noValidate aria-label={kind==='devis'?'Demande de devis':'Formulaire de contact'} onFocus={()=>{started.current ||= Date.now();}}>
    {kind==='devis'&&<ol className="form-progress" aria-label="Progression de votre demande">{['Votre projet','Le périmètre','Vos coordonnées'].map((s,i)=><li key={s} aria-current={i===step?'step':undefined} className={i<step?'step-completed':''}>0{i+1} · {s}</li>)}</ol>}
    <h2 className="form-step-heading" ref={heading} tabIndex={-1}>{kind==='contact'?'Écrivez-nous.':['Commençons par votre idée.','Précisons le besoin.','Faisons connaissance.'][step]}</h2><p className="form-step-description">{kind==='contact'?'Partagez votre besoin. Nous vous répondrons directement.':['Quelques lignes suffisent pour commencer.','Ces éléments nous aident à préparer une proposition adaptée.','Les champs marqués d’un astérisque sont obligatoires.'][step]}</p>
    {kind==='devis'&&step===0&&<><fieldset className="type-fieldset" id="projectType" tabIndex={-1} aria-describedby={errors.projectType?'projectType-error':undefined}><legend className="type-legend">Type de projet *</legend><div className="project-types">{projectTypes.map(t=><label className="project-type" key={t}><input type="radio" name="projectType" id={`projectType-${t}`} value={t} onChange={update} checked={values.projectType===t} aria-describedby={errors.projectType?'projectType-error':undefined} required/>{typeLabels[t]}</label>)}</div>{errors.projectType&&<p className="field-error" id="projectType-error">{errors.projectType}</p>}</fieldset><div className="form-grid"><Field name="objective" label="Quel est l’objectif de votre projet ?" error={errors.objective} wide><textarea {...fieldProps('objective')} onChange={update} maxLength={4000} required placeholder="Présentez votre activité, le problème à résoudre et ce que vous souhaitez obtenir."/></Field></div></>}
    {kind==='devis'&&step===1&&<div className="form-grid"><Field name="features" label="Fonctionnalités principales" optional error={errors.features} wide><textarea {...fieldProps('features')} onChange={update} maxLength={4000} placeholder="Par exemple : catalogue, paiement, espace client, gestion de stock…"/></Field><Field name="budget" label="Budget indicatif" optional error={errors.budget}><select {...fieldProps('budget')} onChange={update}><option value="">Sélectionner</option><option value="a-definir">À définir ensemble</option><option value="moins-1000">Moins de 1 000 USD</option><option value="1000-3000">1 000 à 3 000 USD</option><option value="3000-10000">3 000 à 10 000 USD</option><option value="plus-10000">Plus de 10 000 USD</option></select></Field><Field name="deadline" label="Délai souhaité" optional error={errors.deadline}><select {...fieldProps('deadline')} onChange={update}><option value="">Sélectionner</option><option value="a-definir">À définir</option><option value="1-mois">Dans le mois</option><option value="1-3-mois">Dans 1 à 3 mois</option><option value="3-plus">Dans plus de 3 mois</option></select></Field><Field name="projectStage" label="Votre projet est…" optional error={errors.projectStage} wide><select {...fieldProps('projectStage')} onChange={update}><option value="">Sélectionner</option><option value="nouveau">Un nouveau projet</option><option value="existant">Un projet à moderniser</option></select></Field><Field name="existingUrl" label="Lien du projet existant" optional error={errors.existingUrl} wide><input {...fieldProps('existingUrl')} onChange={update} type="url" maxLength={500} placeholder="https://" autoComplete="url"/></Field><Field name="message" label="Informations complémentaires" optional error={errors.message} wide><textarea {...fieldProps('message')} onChange={update} maxLength={3000} placeholder="Une précision, une contrainte ou une question ?"/></Field></div>}
    {(kind==='contact'||step===2)&&<>{kind==='devis'&&<div className="form-summary"><span>{typeLabels[values.projectType]}</span>{values.projectStage&&<span>{values.projectStage==='nouveau'?'Nouveau projet':'Modernisation'}</span>}</div>}<div className="form-grid">{coordinates}{kind==='contact'&&<><Field name="subject" label="Objet" error={errors.subject} wide><input {...fieldProps('subject')} onChange={update} required maxLength={160} placeholder="Un projet, une question, un partenariat…"/></Field><Field name="objective" label="Votre message" error={errors.objective} wide><textarea {...fieldProps('objective')} onChange={update} required maxLength={4000} placeholder="Comment pouvons-nous vous aider ?"/></Field></>}</div><label className="form-consent"><input id="consent" type="checkbox" name="consent" checked={values.consent} onChange={update} required aria-invalid={!!errors.consent} aria-describedby={errors.consent?'consent-error':undefined}/><span>J’accepte que Nexora Digital utilise ces informations pour traiter ma demande, conformément à la <Link href="/confidentialite">politique de confidentialité</Link>.</span></label>{errors.consent&&<p className="field-error" id="consent-error">{errors.consent}</p>}</>}
    <div className="honeypot" aria-hidden="true"><label htmlFor="website">Votre site personnel</label><input id="website" name="website" value={values.website} onChange={update} tabIndex={-1} autoComplete="off"/></div>
    {failure&&<p className="form-status" role="alert">{failure} Vous pouvez également <a href={site.whatsapp} target="_blank" rel="noopener noreferrer">nous écrire sur WhatsApp</a>.</p>}
    <div className="form-actions">{kind==='devis'&&step>0&&<Button type="button" variant="text" onClick={()=>move(step-1)} disabled={busy}>Retour</Button>}<Button type="submit" disabled={busy}>{busy?'Envoi en cours…':kind==='devis'&&step<2?'Continuer':'Envoyer ma demande'}</Button></div><p className="form-secure-note"><LockKeyhole size={12} aria-hidden="true"/>Vos informations servent uniquement à traiter votre demande.</p>
  </form>;
}
