import Image from 'next/image';
import Link from 'next/link';
import { Check, ShieldCheck, Layers, Sparkles, Gauge, Headphones, CircleCheck, Code2 } from 'lucide-react';
import { Artwork } from '@/components/artwork';
import { ButtonLink, SectionHeading } from '@/components/ui';
import { ServiceCard } from '@/components/service-card';
import { ProjectCard } from '@/components/project-card';
import { FAQList } from '@/components/faq';
import { services, projects, solutions, processSteps, technologyGroups, testimonials, faqs } from '@/data/content';
import { CTA } from './cta';

export function HomeHero(){return <section className="hero"><div className="hero-grid" aria-hidden="true"/><div className="container hero-layout"><div className="hero-copy"><p className="eyebrow hero-eyebrow"><span aria-hidden="true"/> STUDIO DIGITAL · KINSHASA, RDC</p><h1>Votre ambition.<br/>Notre expertise.<br/><span className="text-gradient">Un nouveau cap.</span></h1><p className="hero-description">Sites web, applications et solutions sur mesure pour faire avancer votre entreprise.</p><div className="hero-actions"><ButtonLink href="/devis" data-track="cta_hero">Démarrer un projet</ButtonLink><ButtonLink href="/realisations" variant="secondary">Découvrir nos réalisations</ButtonLink></div><p className="hero-note"><span className="gold-line" aria-hidden="true"/> Du premier échange à la mise en ligne.</p></div><Artwork className="hero-artwork"><Image src="/images/sur-mesure.webp" alt="Un portail numérique aux lignes bleues et dorées, symbole d’une nouvelle perspective" fill sizes="(max-width: 767px) 100vw, 52vw" priority fetchPriority="high" quality={85}/><div className="artwork-label artwork-label-top"><span className="label-corner" aria-hidden="true"/> DE L’IDÉE À L’IMPACT</div><div className="artwork-label artwork-label-bottom"><span>VISION</span><span>DESIGN</span><span>TECHNOLOGIE</span></div></Artwork></div><div className="container hero-bottom"><p>Des solutions pensées pour votre réalité.</p><Link href="#expertises" className="scroll-link">Explorer notre expertise <span aria-hidden="true">↓</span></Link></div></section>;}

export function TrustStrip(){return <section className="trust-strip" aria-label="Nos engagements"><div className="container">{['Solutions sur mesure','Design premium','Technologies modernes','Performance','Accompagnement complet'].map(t=><span key={t}><Check size={15} aria-hidden="true"/>{t}</span>)}</div></section>;}

export function ServicesSection(){return <section className="section services-section" id="expertises"><div className="container"><SectionHeading eyebrow="NOS EXPERTISES" title={<>Le digital, au service<br/>de vos résultats.</>} description="Des solutions qui répondent à un besoin précis. Et qui s’intègrent à la façon dont vous travaillez."><ButtonLink href="/services" variant="text">Découvrir tous nos services <span aria-hidden="true">↗</span></ButtonLink></SectionHeading><div className="services-grid">{services.map(s=><ServiceCard service={s} key={s.slug}/>)}</div></div></section>;}

export function SolutionsSection(){return <section className="section solutions-section"><div className="container solutions-layout"><div className="solutions-intro"><p className="eyebrow">PARTIR DU BON BESOIN</p><h2>Vous avez un défi.<br/><span className="text-soft">Construisons<br/>la réponse.</span></h2><p>Votre projet ne commence pas par une technologie. Il commence par ce que vous voulez changer.</p><ButtonLink href="/solutions" variant="text">Trouver votre solution <span aria-hidden="true">↗</span></ButtonLink><div className="solutions-monogram" aria-hidden="true">N<span>—</span>D</div></div><div className="solutions-list">{solutions.slice(0,4).map(s=><Link href={`/services/${s.service}`} className="solution-row" key={s.number}><span className="solution-number">{s.number}</span><div><p className="solution-tag">{s.tag}</p><h3>{s.question}</h3><p>{s.answer}</p></div><span className="solution-open" aria-hidden="true">↗</span></Link>)}</div></div></section>;}

const principles=[{icon:Layers,title:'Adapté à votre activité',text:'Vos utilisateurs, vos processus et vos contraintes guident la solution.'},{icon:Sparkles,title:'Le soin du détail',text:'Une interface cohérente et des parcours clairs, sur chaque écran.'},{icon:ShieldCheck,title:'Une base sérieuse',text:'Sécurité, maintenabilité et évolution sont prises en compte dès le départ.'},{icon:Headphones,title:'Un partenaire impliqué',text:'Des échanges réguliers et une suite préparée après la mise en ligne.'}];
export function WhySection(){return <section className="section why-section"><div className="container"><SectionHeading eyebrow="L’APPROCHE NEXORA" title="L’exigence, à chaque étape." description="Un produit soigné à l’extérieur. Une construction solide à l’intérieur."/><div className="principles-grid">{principles.map(({icon:Icon,title,text},i)=><article key={title} className="principle"><div className="principle-top"><Icon size={24} aria-hidden="true"/><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>;}

export function ProjectsSection(){return <section className="section projects-section"><div className="container"><SectionHeading eyebrow="NOS RÉALISATIONS" title={<>Des projets.<br/>Des réponses concrètes.</>} description="Découvrez le besoin, les choix et la solution derrière chaque projet."><ButtonLink href="/realisations" variant="text">Voir toutes les réalisations <span aria-hidden="true">↗</span></ButtonLink></SectionHeading><div className="projects-grid">{projects.slice(0,2).map(p=><ProjectCard key={p.slug} project={p} featured/>)}</div></div></section>;}

export function CaseStudySection(){const p=projects[2];return <section className="case-feature"><div className="container case-feature-grid"><div className="case-feature-art"><Image src={p.image} alt={p.imageAlt} fill sizes="(max-width: 767px) 90vw, 45vw"/><span className="case-art-note">VISUEL CONCEPTUEL</span></div><div className="case-feature-copy"><p className="eyebrow">DANS LES COULISSES D’UN PRODUIT</p><h2>Congo Cash.<br/>Du besoin<br/><span className="text-gradient">au prototype.</span></h2><p>Comment penser un parcours de demande de crédit, organiser les rôles et préparer les prochaines intégrations ?</p><span className="badge badge-gold">Prototype en développement</span><div className="case-story"><span><b>01</b> Comprendre</span><span><b>02</b> Structurer</span><span><b>03</b> Construire</span></div><ButtonLink href="/etudes-de-cas/congo-cash" variant="secondary">Explorer l’étude de cas</ButtonLink></div></div></section>;}

export function ProcessSection(){return <section className="section process-section"><div className="container"><SectionHeading eyebrow="UNE MÉTHODE CLAIRE" title="De l’idée à la mise en ligne." description="Vous savez où nous allons, ce qui est livré et ce qui vient ensuite."><ButtonLink href="/processus" variant="text">Découvrir notre processus <span aria-hidden="true">↗</span></ButtonLink></SectionHeading><div className="process-grid">{processSteps.map(p=><article key={p.number}><span className="process-number">{p.number}</span><h3>{p.title}</h3><p>{p.text}</p><span className="process-deliverable"><CircleCheck size={14} aria-hidden="true"/>{p.deliverable}</span></article>)}</div></div></section>;}

export function TechnologiesSection(){return <section className="section technologies-section"><div className="container technology-layout"><div><p className="eyebrow">LES BONS OUTILS</p><h2>Une technologie<br/>choisie pour<br/><span className="text-soft">votre projet.</span></h2><p>Nous choisissons la stack selon les usages, la performance et les évolutions prévues.</p><div className="technology-icons" aria-hidden="true"><Code2/><Gauge/></div></div><div className="technology-groups">{technologyGroups.map(g=><div key={g.label}><h3>{g.label}</h3><div>{g.items.map(t=><span key={t}>{t}</span>)}</div></div>)}</div></div></section>;}
export function TestimonialsSection(){const approved=testimonials.filter(t=>t.approved);if(!approved.length)return null;return <section className="section"><div className="container"><SectionHeading eyebrow="LEURS RETOURS" title="Une collaboration qui se raconte."/><div className="testimonials-grid">{approved.map(t=><figure key={t.name}><blockquote>{t.quote}</blockquote><figcaption>{t.name} · {t.role}</figcaption></figure>)}</div></div></section>;}
export function HomeFAQ(){return <section className="section home-faq"><div className="container faq-layout"><div><p className="eyebrow">AVANT DE SE LANCER</p><h2>Quelques<br/>réponses utiles.</h2><ButtonLink href="/faq" variant="text">Toutes les questions <span aria-hidden="true">↗</span></ButtonLink></div><FAQList items={faqs.slice(0,4)}/></div></section>;}
export function HomePage(){return <><HomeHero/><TrustStrip/><ServicesSection/><SolutionsSection/><WhySection/><ProjectsSection/><CaseStudySection/><ProcessSection/><TechnologiesSection/><TestimonialsSection/><HomeFAQ/><CTA/></>;}
